FROM mcr.microsoft.com/playwright/python:v1.53.0-noble

WORKDIR /app

COPY pyproject.toml uv.lock ./ 

RUN pip install uv && uv sync && pip install -e .

COPY . .

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "api.api:app", "--host", "0.0.0.0", "--port", "8000"]