FROM mcr.microsoft.com/playwright/python:v1.53.0-noble

WORKDIR /app

COPY pyproject.toml uv.lock ./ 

RUN pip install uv && uv sync && pip install -e .
RUN apt-get update && apt-get install -y ffmpeg --no-install-recommends && rm -rf /var/lib/apt/lists/*

COPY . .

CMD ["python", "-m", "src.worker"]
