FROM mcr.microsoft.com/playwright/python:v1.54.0-noble

WORKDIR /app

COPY pyproject.toml uv.lock ./ 

RUN pip install uv && uv sync && pip install -e .

# Install ffmpeg for pydub
RUN apt-get update && apt-get install -y ffmpeg

COPY . .

CMD ["python", "-m", "src.worker"]
